name:                advent-of-code-y2025
version:             0.1.0.0
github:              "odilf/advent-of-code-2025"
license:             BSD-3-Clause
author:              "Odilf"
# maintainer:          "example@example.com"
copyright:           "2025 Odilf"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/odilf/advent-of-code-2025#readme>

dependencies:
- base >= 4.7 && < 5
- req
- text
- bytestring
- dotenv
- directory
- parsec
- unordered-containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded
- -rtsopts
- -with-rtsopts=-N
# To be more concise in day solutions
- -Wno-missing-signatures
- -Wno-type-defaults

library:
  source-dirs: src


executables:
  day1:
    main: Day1.hs
    source-dirs: solutions
    other-modules: []
    dependencies:
    - advent-of-code-y2025
  day2:
    main: Day2.hs
    source-dirs: solutions
    other-modules: []
    dependencies:
    - advent-of-code-y2025
  day3:
    main: Day3.hs
    source-dirs: solutions
    other-modules: []
    dependencies:
    - advent-of-code-y2025
  day4:
    main: Day4.hs
    source-dirs: solutions
    other-modules: []
    dependencies:
    - advent-of-code-y2025
  day5:
    main: Day5.hs
    source-dirs: solutions
    other-modules: []
    dependencies:
    - advent-of-code-y2025

tests:
  advent-of-code-y2025-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2025
